on: [push]

jobs:
  test_and_validate:
    runs-on: ubuntu-latest
    name: Job to validate and test WDL
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        run: |
             wget -O /tmp/cromwell.jar https://github.com/broadinstitute/cromwell/releases/download/79/cromwell-79.jar
             wget -O /tmp/womtool.jar https://github.com/broadinstitute/cromwell/releases/download/79/womtool-79.jar
             java -version
      - name: Prepare
        run: |
             make prep
             make testarea
      - name: Validate WDL
        run: |
          java -jar /tmp/womtool.jar validate nmdc-metag_full.wdl
      - name: Validate metadata generation
        run: |
          make testmetadata
